# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wer're Not Qualified Podcast
email: wnqpod@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://garv5014.github.io/WnqPodcast/" # the subpath of your site, e.g. /blog
url: "https://garv5014.github.io/WnqPodcast/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

podcast:
  title: We're Not Qualified
  description: [ A podcast that was birthed out of the random conversations that are had between friends. We cover a wide range of topics that you guessed it!! We aren't qualified to talk about
   We are not qualified sources for any of the topics that are discussed. 
 ]
  url: https://garv5014.github.io/WnqPodcast/podcast.xml # podcast xml url
  author: [We're Not Qualified]
  email: [wnqpod@gmail.com]
  logo: [https://wnq-podcast2022.s3.us-west-2.amazonaws.com/LogoWNQ.png] # logo in 1400 – 3000 pixel
  language: [en-us] # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: [Comedy] # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: []
  type: [Episodic] # episodic | serial
  explicit: [false] # true | false
  complete: [yes] # 'yes' | 'no'
  block: [no] # 'yes' | 'no'

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
